// export * from './address.controller';
export * from './alumni-degree.controller';
// export * from './alumni-user.controller';
export * from './alumni.controller';
export * from './degree-alumni.controller';
export * from './media.controller';
export * from './policy.controller';
export * from './post-audio.controller';
export * from './post-document.controller';
export * from './post-photo.controller';
export * from './post-post-config.controller';
export * from './post-user.controller';
export * from './post-video.controller';
export * from './post.controller';
export * from './school-address.controller';
// export * from './school-alumni.controller';
export * from './school-audio.controller';
export * from './school-document.controller';
export * from './school-photo.controller';
export * from './school-post.controller';
export * from './school-school-details.controller';
export * from './school-user.controller';
export * from './school-video.controller';
export * from './school.controller';
export * from './user-address.controller';
// export * from './user-alumni.controller';
export * from './user-photo.controller';
export * from './user-post.controller';
export * from './user-school.controller';
export * from './user-user-config.controller';
export * from './user.controller';
// export * from './photo-post.controller';
export * from './post-photo-through.controller';
export * from './post-video-through.controller';
export * from './post-audio-through.controller';
export * from './post-document-through.controller';
export * from './user-video.controller';
export * from './user-audio.controller';
export * from './user-document.controller';
export * from './user-comment.controller';
export * from './user-comment.controller';
export * from './post-comment.controller';
export * from './comment-user.controller';
export * from './like.controller';
export * from './comment.controller';
